apiVersion: v1
kind: ServiceAccount
metadata:
  name: bridge-watch
  namespace: bridge-watch
  labels:
    app.kubernetes.io/name: bridge-watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bridge-watch-role
  namespace: bridge-watch
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bridge-watch-rolebinding
  namespace: bridge-watch
subjects:
  - kind: ServiceAccount
    name: bridge-watch
    namespace: bridge-watch
roleRef:
  kind: Role
  name: bridge-watch-role
  apiGroup: rbac.authorization.k8s.io
