import type { FastifyInstance } from "fastify";
import { assetsRoutes } from "./assets.js";
import { bridgesRoutes } from "./bridges.js";
import { websocketRoutes } from "./websocket.js";
import { alertsRoutes } from "./alerts.routes.js";
import { circuitBreakerRoutes } from "./circuitBreaker.js";
import { preferencesRoutes } from "./preferences.js";
import { apiKeysRoutes } from "./apiKeys.js";
import jobsRoutes from "./jobs.js";
import { configRoutes } from "./config.js";
import { aggregationRoutes } from "./aggregation.js";
import { metadataRoutes } from "./metadata.js";
import { analyticsRoutes } from "./analytics.js";
import { watchlistsRoutes } from "./watchlists.js";
import { cacheRoutes } from "./cache.js";
import { healthRoutes } from "./health.js";
import { rateLimitAdminRoutes } from "./rateLimitAdmin.js";
import { tracingAdminRoutes } from "./tracingAdmin.js";
import { validationAdminRoutes } from "./validationAdmin.js";
import { metricsRoutes } from "./metrics.js";

export async function registerRoutes(server: FastifyInstance) {
  server.register(assetsRoutes, { prefix: "/api/v1/assets" });
  server.register(bridgesRoutes, { prefix: "/api/v1/bridges" });
  server.register(websocketRoutes, { prefix: "/api/v1/ws" });
  server.register(alertsRoutes, { prefix: "/api/v1/alerts" });
  server.register(circuitBreakerRoutes, { prefix: "/api/v1/circuit-breaker" });
  server.register(preferencesRoutes, { prefix: "/api/v1/preferences" });
  server.register(apiKeysRoutes, { prefix: "/api/v1/admin/api-keys" });
  server.register(jobsRoutes, { prefix: "/api/v1/jobs" });
  server.register(configRoutes, { prefix: "/api/v1/config" });
  server.register(aggregationRoutes, { prefix: "/api/v1/aggregation" });
  server.register(metadataRoutes, { prefix: "/api/v1/metadata" });
  server.register(analyticsRoutes, { prefix: "/api/v1/analytics" });
  server.register(watchlistsRoutes, { prefix: "/api/v1/watchlists" });
  server.register(cacheRoutes, { prefix: "/api/v1/cache" });
  server.register(healthRoutes, { prefix: "/health" });
  server.register(rateLimitAdminRoutes, { prefix: "/api/v1/admin/rate-limit" });
  server.register(tracingAdminRoutes, { prefix: "/api/v1/admin/tracing" });
  server.register(validationAdminRoutes, { prefix: "/api/v1/admin/validation" });
  server.register(metricsRoutes, { prefix: "/metrics" });
}
